services:
  db:
    image: postgres:18-alpine
    container_name: sts-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: sts
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sts_backup.sql:/docker-entrypoint-initdb.d/01-sts_backup.sql:ro

  # backend:
  #   build:
  #     context: ./nest-backend
  #     dockerfile: Dockerfile
  #   container_name: sts-backend
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - .env
  #   environment:
  #     - NODE_ENV=development
  #     - DB_HOST=db
  #   volumes:
  #     - ./nest-backend:/app
  #     - /app/node_modules
  #   command: npm run start:dev
  #   depends_on:
  #     - db

  # frontend:
  #   build:
  #     context: ./quasar-frontend
  #     dockerfile: Dockerfile
  #   container_name: sts-frontend
  #   restart: always
  #   ports:
  #     - "9001:9001"
  #   environment:
  #     - BACKEND_URL=http://localhost:3000
  #   volumes:
  #     - ./quasar-frontend:/app
  #     - /app/node_modules
  #   depends_on:
  #     - backend

volumes:
  postgres_data:
